sudo pacman -R --noconfirm mousepad 
sudo pacman -R --noconfirm vim 
sudo pacman -R --noconfirm xfburn 
sudo pacman -R --noconfirm ristretto 
sudo pacman -R --noconfirm parole 
sudo pacman -R --noconfirm xfce4-battery-plugin
sudo pacman -R --noconfirm xfce4-calculator-plugin
sudo pacman -R --noconfirm xfce4-clipman-plugin
sudo pacman -R --noconfirm xfce4-cpufreq-plugin
sudo pacman -R --noconfirm xfce4-cpugraph-plugin
sudo pacman -R --noconfirm xfce4-diskperf-plugin
sudo pacman -R --noconfirm xfce4-eyes-plugin
sudo pacman -R --noconfirm xfce4-fsguard-plugin
sudo pacman -R --noconfirm xfce4-mailwatch-plugin
sudo pacman -R --noconfirm xfce4-mount-plugin
sudo pacman -R --noconfirm xfce4-mpc-plugin
sudo pacman -R --noconfirm xfce4-netload-plugin
sudo pacman -R --noconfirm xfce4-notes-plugin
sudo pacman -R --noconfirm xfce4-places-plugin
sudo pacman -R --noconfirm xfce4-sample-plugin
sudo pacman -R --noconfirm xfce4-sensors-plugin
sudo pacman -R --noconfirm xfce4-smartbookmark-plugin
sudo pacman -R --noconfirm xfce4-stopwatch-plugin
sudo pacman -R --noconfirm xfce4-systemload-plugin
sudo pacman -R --noconfirm xfce4-timer-plugin
sudo pacman -R --noconfirm xfce4-time-out-plugin
sudo pacman -R --noconfirm xfce4-verve-plugin
sudo pacman -R --noconfirm xfce4-wavelan-plugin
sudo pacman -R --noconfirm xfce4-weather-plugin
sudo pacman -R --noconfirm xfce4-whiskermenu-plugin
sudo pacman -R --noconfirm xfce4-whiskermenu-plugin
sudo pacman -R --noconfirm xfce4-taskmanager
